#!/bin/sh -e
# Copyright 2020 Balbir Thomas
# See LICENSE file for licensing details.

if [ -z "$VIRTUAL_ENV" -a -d venv/ ]; then
    . venv/bin/activate
fi

if [ -z "$PYTHONPATH" ]; then
    export PYTHONPATH="src:lib"
else
    export PYTHONPATH="src:lib:$PYTHONPATH"
fi

black --diff
python3 -m unittest -v "$@"
