name: Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  pull-request:
    name: PR
    uses: canonical/observability/.github/workflows/pull-request.yaml@main
    with:
      component: prometheus
    secrets: inherit
