name: Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  pull-request:
    uses: canonical/observability/.github/workflows/pull-request.yaml@main
    with:
      component: prometheus
    secrets:
      CHARMHUB_TOKEN: ${{ secrets.CHARMHUB_TOKEN }}
