name: Pull Requests

on:
  pull_request:
    branches:
      - main
      - track/**

permissions:
  # Required for CodeQL security scanning
  security-events: write
  # Required for private repositories
  actions: read
  contents: read

jobs:
  pull-request:
    name: PR
    uses: canonical/observability/.github/workflows/charm-pull-request.yaml@v1
    secrets: inherit
