name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  lib-check:
    name: Check libraries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check libs
        uses: canonical/charming-actions/check-libraries@1.0.1-rc
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          comment-on-pr: false
          fail-build: true

  static-lib:
    name: Static analysis of /lib for Python 3.5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.5
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run static analysis for /lib for 3.5
        run: tox -vve static-lib

  static-charm:
    name: Static analysis of the charm and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run static analysis (charm)
        run: tox -vve static-charm
      - name: Run static analysis (unit tests)
        run: tox -vve static-unit
      - name: Run static analysis (integration tests)
        run: tox -vve static-integration

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run linters
        run: tox -vve lint

  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: python -m pip install tox
      - name: Run tests
        run: tox -e unit

  integration-test:
    name: Integration tests (microk8s)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          juju-channel: latest/stable
          provider: microk8s
      - name: Run Prometheus integration tests
        run: tox -vve integration
