name: Pull Requests

on:
  pull_request:
    branches:
      - main
      - track/**

jobs:
  pull-request:
    name: PR
    uses: canonical/observability/.github/workflows/charm-pull-request.yaml@v1
    secrets: inherit
