name: Pull Requests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - test-tempo-error
jobs:
  pull-request:
    name: PR
    uses: canonical/observability/.github/workflows/charm-pull-request.yaml@enable-debug
    secrets: inherit
